name: SonarQube Analysis

on:
  push:
    branches:
      - main  # ou a branch que você deseja monitorar

jobs:
  sonarQube:
    runs-on: ubuntu-latest

    services:
      sonar:
        image: sonarqube:latest
        options: --health-cmd="curl -f http://localhost:9000/api/health" --health-interval=10s --health-timeout=5s --health-retries=3
        ports:
          - 9000:9000
        options: --detach  # para rodar em segundo plano

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Run SonarQube Scanner
      run: |
        docker run --rm \
          -v $(pwd):/usr/src \
          -e SONAR_HOST_URL="http://localhost:9000" \
          sonarsource/sonar-scanner-cli

    - name: Upload SonarQube report as an artifact
      uses: actions/upload-artifact@v3
      with:
        name: sonarqube-report
        path: .scannerwork  # Pasta onde o SonarQube armazena o relatório
